config/routes.rb
Posh::Application.routes.draw do
 
  get "users/update"

  get "users/index"

  resources :restaurants

  resources :tables

  resources :users
  resources :sessions
  resources :menus
    

  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',    to: 'static_pages#about'
  match '/contact',    to: 'static_pages#contact'
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  
  
    get "order/:table_id" => "orders#show"
    match 'place_order' => 'orders#place_order', :via => [:get, :post]
  

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  attr_accessible :category, :description, :happyhourfrom, :happyhourprice, :happyhourto,  
  :image, :remote_image_url, :picture, :price, :title, :restaurant_id, :displayonmobilemenu_id


  mount_uploader :image, ImageUploader
  
  validates :category, :title, :price, presence: true
  belongs_to :restaurants
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @menus }
    end
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
    @menu = Menu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/new
  # GET /menus/new.json
  def new
    @menu = Menu.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/1/edit
  def edit
    @menu = Menu.find(params[:id])
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(params[:menu])

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render json: @menu, status: :created, location: @menu }
      else
        format.html { render action: "new" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /menus/1
  # PUT /menus/1.json
  def update
    @menu = Menu.find(params[:id])

    respond_to do |format|
      if @menu.update_attributes(params[:menu])
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to menus_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_form.html.erb
<br><br>
<%= form_for(@menu, :html => {:multipart => true}) do |f| %>
  <%= f.hidden_field :restaurant_id, :value => current_user.activeRestaurant_id %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   
  
  <div class="row showgrid menu-list"> 
        
          <div class="span2">
          <div class="thumbnail float-left">
            <img src="http://res.cloudinary.com/zonarplanet-com/image/upload/sample.jpg" alt="">
            <%= f.label "Change the image" %><br />
            <!-- %= f.text_field :image % -->
            <%= f.file_field :image %>
          </div>
          
          </div> <!-- span2 -->
          
          <div class="span6">
            <div class="field">
              <%= f.label :category %><br />
              <%= f.text_field :category %>
            </div> <br>      
            <div class="field">
              <%= f.label :title %><br />
              <%= f.text_field :title %>
             </div>
     
           <div class="menu-explanation">
             <div class="field">
               <%= f.label :description %><br />
               <%= f.text_area :description, rows: 4 %>
             </div>
             <p>Happy hour</p>
             <div class="field">
              <%= f.label :happyhourfrom %><br />
              <%= f.time_select :happyhourfrom %>
             </div>
             <div class="field">
              <%= f.label :happyhourto %><br />
              <%= f.time_select :happyhourto %>
             </div>
             <div class="field">
               <%= f.label :happyhourprice %><br />
               <%= f.text_field :happyhourprice %>
             </div>
           </div>
       
           
           
          </div> <!-- span6 -->
        
       <div class="span2">
         <div class="field">
           <%= f.label :price %><br />
           <%= f.text_field :price %>
         </div>
       </div>
       <div class="span3">
 	      <div class="actions ">
           <%= f.submit 'Commit', :class => 'btn btn-primary btn-large' %>
          </div>
      </div>
       
      </div> <!-- row -->
<% end %>

app/views/menus/edit.html.erb
<br><br>
<h1>Editing menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<br><br>
<h1>The Main Menu</h1>
<h2>This list of menu items reflects all menus available for all the restaurants</h2>
<h2>managed by the user currently logged in.</h2>
<p>Please select the menu Items you want to display for the active restaurants menu display.</p>

  
     <!-- div class="menu_item"  -->
     
      <% @menus.each do |menu| %>
       <div class="row showgrid menu-list"> 
        
          <div class="span2">
          <div class="thumbnail float-left">
         <img src="http://placehold.it/50x50" alt="">
          <%= menu.image %>
          </div>
          </div>
          <div class="span6">
 
            <!-- h2><%= menu.category %></h2><br  -->      
            <h3><%= menu.title %></h3><br>
     
           <div class="menu-explanation">
             <p><%= truncate(strip_tags(menu.description), length: 80) %></p>
             <p><%= menu.happyhourfrom.strftime("%H.%M %p") %></p>
             <p><%= menu.happyhourto.strftime("%H.%M %p") %></p>
             <p><%= menu.happyhourprice %></p>
           </div>
       
           
           
          </div> <!-- span6 -->
        
       <div class="span2">
        <h1 class="menu-list"><%= menu.price %></h1>

		<%= form_for(menu, :html => {:multipart => true}) do |f| %>
		  <%= f.hidden_field :restaurant_id, :value => current_user.activeRestaurant_id %>
		  <% if menu.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

		      <ul>
		      <% menu.errors.full_messages.each do |msg| %>
		        <li><%= msg %></li>
		      <% end %>
		      </ul>
		    </div>
		  <% end %>

		<p><%= f.check_box :displayonmobilemenu_id %></p>
		<div class="actions ">
	       <%= f.submit 'Commit', :class => 'btn btn-primary btn-large' %>
	      </div>
	<% end %> <!-- form -->
	
       </div>
       <div class="span3">
			<% if menu.restaurant_id %>
			 <p>"DEBUG restaurant reference: "<%= menu.restaurant_id %></p>
			 <% end %>
 	      <dl >
		   	<dd><%= link_to "Add to cart", '', class: "btn btn-small btn-primary" %> 
			   </dd>
 	       <dt>
 	        <%= link_to 'Show', menu %>
 	       </dt>
 	       <dt>
 	         <%= link_to 'Edit', edit_menu_path(menu) %>
 	       </dt>
 	       <dt>
 	         <%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %>
 	       </dt>
 	      </dl>
      </div>
 	   
      
      </div> <!-- row -->
     

<% end %>


      


 <!-- /div --> <!-- menu-item -->
<br />

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<br><br>
<h1>New menu</h1>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<br><br>
<p id="notice"><%= notice %></p>


<div class="row showgrid menu-list"> 
        
          <div class="span2">
          <div class="thumbnail float-left">
         <img src="http://res.cloudinary.com/zonarplanet-com/image/upload/sample.jpg" alt="">
          <%= @menu.image %>
          </div>
          </div>
          <div class="span6">
            <p>Category :
            <%= @menu.category %></P><br>      
            <h3><%= @menu.title %></h3><br>
     
           <div class="menu-explanation">
             <p><%= truncate(strip_tags(@menu.description), length: 80) %></p>
             <p>Happy hour</p>
             <p><%= @menu.happyhourfrom.strftime("%H.%M %p") %></p>
             <p><%= @menu.happyhourto.strftime("%H.%M %p") %></p>
             <p><%= @menu.happyhourprice %></p>
           </div>
       
           
           
          </div> <!-- span6 -->
        
       <div class="span2">
        <h1 class="menu-list"><%= @menu.price %></h1>
       </div>
       <div class="span3">
 	      <dl >
 	       <dt>
 	        <%= link_to 'Edit', edit_menu_path(@menu) %>
 	       </dt>
 	       <dt>
 	         <%= link_to 'Back', menus_path %>
 	       </dt>
 	      </dl>
      </div>
       
      </div> <!-- row -->