config/routes.rb
Posh::Application.routes.draw do
 
  get "users/update"

  get "users/index"

  resources :restaurants

  resources :tables

  resources :users
  resources :sessions
  resources :menus
    

  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',    to: 'static_pages#about'
  match '/contact',    to: 'static_pages#contact'
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  
  
    get "order/:table_id" => "orders#show"
    match 'place_order' => 'orders#place_order', :via => [:get, :post]
  

end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tables }
    end
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
    @table = Table.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @table }
    end
  end

  # GET /tables/new
  # GET /tables/new.json
  def new
    @table = Table.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @table }
    end
  end

  # GET /tables/1/edit
  def edit
    @table = Table.find(params[:id])
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(params[:table])

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render json: @table, status: :created, location: @table }
      else
        format.html { render action: "new" }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tables/1
  # PUT /tables/1.json
  def update
    @table = Table.find(params[:id])

    respond_to do |format|
      if @table.update_attributes(params[:table])
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table = Table.find(params[:id])
    @table.destroy

    respond_to do |format|
      format.html { redirect_to tables_url }
      format.json { head :no_content }
    end
  end
end

def generateTables( numberoftables=0)
  $i = 0;
  until $i == numberoftables do
    @table = Table.new
    @table.tablenumber=$i
    @table.save
  end
  
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/_form.html.erb
<br><br>
<%= form_for(@table) do |f| %>
  <%= f.hidden_field :restaurant_id, :value => current_user.activeRestaurant_id %>
  <% if @table.errors.any? %>
   <div id="error_explanation">
      <h2><%= pluralize(@table.errors.count, "error") %> prohibited this table from being saved:</h2>
     <ul>
        <% @table.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
<div class="row showgrid table-list"> 
    <div class="span2">
          <div class="thumbnail float-left">
         <img src="http://res.cloudinary.com/zonarplanet-com/image/upload/sample.jpg" alt="">
          <!-- %= @menu.picture % -->
          </div>
          </div>
          <div class="span6 table-explanation">
            <div class="field">
             <%= f.label :tablenumber %><br />
             <%= f.text_field :tablenumber %>
          </div>
         <div class="field">
           <%= f.label :tablename %><br />
           <%= f.text_field :tablename %>
         </div>
          </div> <!-- span6 -->
        
       
       <div class="span3 last">
 	       
        <div class="actions">
          <%= f.submit 'Update table', :class => 'btn btn-primary btn-large' %>
        </div>

      </div>
       
      </div> <!-- row -->
<% end %>

app/views/tables/edit.html.erb
<br><br>
<h1>Editing table</h1>

<%= render 'form' %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

app/views/tables/index.html.erb
<h1>Manage tables</h1>

<!-- create the code for creating several tables at once. in the controller is already the method -->



 <% @tables.each do |table| %>
       <div class="row showgrid table-list"> 
        
          <div class="span2">
          <div class="thumbnail float-left">
         <img src="http://placehold.it/50x50" alt="">
          <!-- %= table.picture % -->
          </div>
          </div>
          <div class="span6">
      
            <h3><%= "Table number: "+table.tablenumber %></h3><br>
     
           <div class="table-explanation">
             <p><%= "Table name: "+table.tablename %></p>
             <% if table.restaurant_id %>
			 <p>"DEBUG restaurant reference: "<%= table.restaurant_id %></p>
			 <% end %>
           </div>
         
          </div> <!-- span6 -->
        
       <div class="span2">
       </div>
       <div class="span3">
 	      <dl >
 	       <dt>
 	        <%= link_to 'Show', table %>
 	       </dt>
 	       <dt>
 	         <%= link_to 'Edit', edit_table_path(table) %>
 	       </dt>
 	       <dt>
 	         <%= link_to 'Destroy', table, method: :delete, data: { confirm: 'Are you sure?' } %>
 	       </dt>
 	      </dl>
      </div>
 	   
      
      </div> <!-- row -->
     

<% end %>

<br />

<%= link_to 'New Table', new_table_path %>

app/views/tables/new.html.erb
<br><br>
<h1>New table</h1>

<%= render 'form' %>

<%= link_to 'Back', tables_path %>

app/views/tables/show.html.erb
<br><br>
<p id="notice"><%= notice %></p>


<br><br>
<div class="row showgrid table-list"> 
        
    <div class="span2">
          <div class="thumbnail float-left">
         <img src="http://res.cloudinary.com/zonarplanet-com/image/upload/sample.jpg" alt="">
          <!-- %= @menu.picture % -->
          </div>
          </div>
          <div class="span5 table-explanation">
            <p>
              <!-- generate the URL for submitting for the QR code -->
              <p><%= request.host_with_port+table_path(@table) %></p>
              <b>Tablenumber:</b>
              <%= @table.tablenumber %>
            </p>
            <p>
              <b>Tablename:</b>
              <%= @table.tablename %>
            </p>
          </div> <!-- span6 -->
        
       
       <div class="span5 last">
 	      <dl >
 	       <dt>
 	        <%= link_to 'Edit', edit_table_path(@table) %>
 	       </dt>
 	       <dt>
 	         <%= link_to 'Back', tables_path %>
 	       </dt>
		   <dt>
 	         <%= link_to 'Make new Order',  %>
 	       </dt>
		   <dt>
 	         <%= link_to 'List orders',  %>
 	       </dt>
 	      </dl>
      </div>
       
      </div> <!-- row -->