config/routes.rb
Posh::Application.routes.draw do
 
  get "users/update"

  get "users/index"

  resources :restaurants

  resources :tables

  resources :users
  resources :sessions
  resources :menus
    

  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',    to: 'static_pages#about'
  match '/contact',    to: 'static_pages#contact'
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  
  
    get "order/:table_id" => "orders#show"
    match 'place_order' => 'orders#place_order', :via => [:get, :post]
  

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  attr_accessible :city, :country, :franchise, :name, :numberOfStaffPrShift, :phone, :restaurantSize, 
                  :restaurantType, :state, :street, :zip, :user_id

  belongs_to :user
  validates :user_id, presence: true
  has_many :tables, dependent: :destroy
  has_many :menus, dependent: :destroy
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @restaurants }
    end
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @restaurant }
    end
  end

  # GET /restaurants/new
  # GET /restaurants/new.json
  def new
    @restaurant = Restaurant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @restaurant }
    end
  end

  # GET /restaurants/1/edit
  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    #@user = User.find(params[:user_id])
    @restaurant = Restaurant.new(params[:restaurant])
    #@restaurant = @user.restaurant.build(params[:list])
    
    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render json: @restaurant, status: :created, location: @restaurant }
      else
        format.html { render action: "new" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /restaurants/1
  # PUT /restaurants/1.json
  def update
    @restaurant = Restaurant.find(params[:id])

    respond_to do |format|
      if @restaurant.update_attributes(params[:restaurant])
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
	<%= f.hidden_field :user_id, :value => current_user.id %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Restaurant name" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label "Restaurant size" %><br />
    <%= f.text_field :restaurantSize %>
  </div>
  <div class="field">
    <%= f.label "Number of staff pr shift" %><br />
    <%= f.number_field :numberOfStaffPrShift %>
  </div>
  <div class="field">
    <%= f.label "Restautant type" %><br />
    <%= f.text_field :restaurantType %>
  </div>
  <div class="field">
    <%= f.label :franchise %><br />
    <%= f.check_box :franchise %>
  </div>
  <div class="actions">
    <%= f.submit 'Commit', :class => 'btn btn-primary btn-large' %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<h1>Listing restaurants</h1>

<table>
 


<% @restaurants = Restaurant.where(:user_id => current_user.id) %>
<% @restaurants.each do |restaurant| %>
   <div class="row showgrid"> 
    
      <div class="span6">   
        <h3><%= restaurant.name %></h3><br>
 
       <div class="">
		 <p><%= restaurant.street %></p>
	     <p><%= restaurant.city %></p>
		 <p><%= restaurant.state %></p>
		 <p><%= restaurant.zip %></p>
		 <p><%= restaurant.country %></p>
	     <p><%= restaurant.phone %></p>
         <p><%= restaurant.restaurantSize %></p>
         <p><%= restaurant.numberOfStaffPrShift %></p>
         <p><%= restaurant.restaurantType %></p>
         <p><%= restaurant.franchise %></p>
       </div>
   
       
       
      </div> <!-- span6 -->
    
   <div class="span3">
      <dl >
	   	
       <dt>
        <%= link_to 'Show', restaurant %>
       </dt>
       <dt>
         <%= link_to 'Edit', edit_restaurant_path(restaurant) %>
       </dt>
       <dt>
         <%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %>
       </dt>
      </dl>
  </div>
   
  
  </div> <!-- row -->
 

<% end %>

<!-- /div --> <!-- restaurant -->

<br />

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<br><br>
<p id="notice"><%= notice %></p>

<div class="row showgrid"> 
<div class="span6">
	
<p>
  <b>Restaurant name:</b>
  <%= @restaurant.name %>
</p>

<div class="">
<p>
  <b>Street:</b>
  <%= @restaurant.street %>
</p>

<p>
  <b>City:</b>
  <%= @restaurant.city %>
</p>

<p>
  <b>State:</b>
  <%= @restaurant.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @restaurant.zip %>
</p>

<p>
  <b>Country:</b>
  <%= @restaurant.country %>
</p>

<p>
  <b>Phone:</b>
  <%= @restaurant.phone %>
</p>

<p>
  <b>Restaurant size:</b>
  <%= @restaurant.restaurantSize %>
</p>

<p>
  <b>Number of staff pr. shift:</b>
  <%= @restaurant.numberOfStaffPrShift %>
</p>

<p>
  <b>Restaurant type:</b>
  <%= @restaurant.restaurantType %>
</p>

<p>
  <b>Franchise:</b>
  <%= @restaurant.franchise %>
</p>
</div>
 </div> <!-- span6 -->

<div class="span3">

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

</div>
   
  </div> <!-- row -->