config/routes.rb
Posh::Application.routes.draw do
 
  get "users/update"

  get "users/index"

  resources :restaurants

  resources :tables

  resources :users
  resources :sessions
  resources :menus
    

  root to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',    to: 'static_pages#about'
  match '/contact',    to: 'static_pages#contact'
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  
  
    get "order/:table_id" => "orders#show"
    match 'place_order' => 'orders#place_order', :via => [:get, :post]
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.tabletab.sg/">TABLETAB</a>
    by Michael Nielsen and Michael Hansen
  </small>
  <nav>
	
    <ul>
	   <li>
		 <% if current_user %>
		    Logged in as <%= current_user.email %>.
		    <%= link_to "Log out", log_out_path %>
		  <% else %>
		    <%= link_to "Sign up", sign_up_path %> or
		    <%= link_to "log in", log_in_path %>
		  <% end %>
		</li>
		<% if not current_user %>
	  	<li><%= link_to " Home ",    root_path %></li>
          <li><%= link_to " Help ",    help_path %></li>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://www.tabletab.sg/">TABLETAB news</a></li>
      <% end %>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!--
<header class="navbar navbar-fixed-top">
	
  <div class="navbar-inner" >
    <div class="container" >
-->	 	
	<!--
      <%= link_to "TABLETAB", root_path, id: "logo" %>
     --> 

   <!--  
     
    </div>
  </div>
</header>

-->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
	 <!--Mobile specific meta goodness :)-->
	<!-- meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" -->
	
    <%= render 'layouts/shim' %>  
    
  </head>

<% if current_user %>
	<body id="tabletabPage">
<% else %>
  <body id="tabletabPage">
<% end %>

    <!-- The fixed header-->
	<script type="text/javascript">

	window.onload = function() {
	$('.dropdown-toggle').dropdown();
	}

	</script>
	<div class="navbar navbar-fixed-top" id="tabletab-nav">
		<div class="navbar-inner" id="tabletab-nav">
			<!-- Iphone View Menu Button -->
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			</a>
			<div class="nav-collapse">	
				<ul class="nav">
					<% if current_user %>
						<li><%= link_to "Manage MENU", menus_path, tabindex: "-1" %></li>
						<li><%= link_to "Manage TABLES", tables_path %></li>
						<li><%= link_to "Manage RESTAURANT", restaurants_path %></li>
						<li class="divider"></li>
					<% end %>
					<li><%= link_to " Home ",    root_path %></li>
					<li><%= link_to "About",   about_path %></li>
					<li><%= link_to "Contact", contact_path %></li>
					<li><%= link_to " Help ",    help_path %></li>
					<% if current_user %>
			    	<li><%= link_to "Log out", log_out_path %></li>
					<% end %>
				</ul>
			</div>
			<!--div class="nav pull-right">
				<a class="brand" href="#">Restaurant Name</a>
			</div -->
			
		</div>
	</div>
	<%= gflash %>
	<div> 
		
	  <%= yield %>
    
   </div>
       <!-- %= render 'layouts/footer' % -->
    <!-- the bottom bar-->
	<!-- div id="BottomDiv">
		Welcome to Tabletab - you are logged in as:</div -->
		
		<div class="navbar navbar-inverse navbar-fixed-bottom" id="tabletab-nav">
			<div class="navbar-inner" id="tabletab-nav">
				<!-- div class="container"  id="tabletab-nav" -->



					<div class="nav" role="navigation">
						<% if current_user %>
							<p>Welcome to Tabletab - you are logged in as: <%= current_user.name %> - ROLE <%= link_to "Log out", log_out_path %>  ---   <%= link_to "Go to your profile", current_user %>  --- Active Restaurant: <%= current_user.activeRestaurant_id %> </p>
						<% else %>
							<p>Welcome to Tabletab - <%= link_to "Click here to login", log_in_path %> </p>
						<% end %>
					</div>
				<!--/div -->
			</div>
		</div>
		

      <%= debug(params) if Rails.env.development? %>
    
    
	<!-- <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript" charset="utf-8"></script> -->

 
  </body>
</html>